run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []

issues:
  exclude-dirs:
    - vendor
    - generated
  exclude-files:
    - ".*\\.pb\\.go$"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/your-org/your-repo
  revive:
    min-confidence: 0.8
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  lll:
    line-length: 120
  mnd:
    ignored-numbers:
      - '0666'
      - '0755'
      - '42'

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - asciicheck # Too restrictive for LaTeX code
    - funlen # Allow longer functions
    - gochecknoglobals # Allow global variables
    - gocognit # Allow complex functions
    - godot # Allow missing final period
    - godox # Allow TODO comments

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit

    # Allow longer function names in main packages
    - path: cmd/
      linters:
        - lll

    # Allow magic numbers in test files
    - path: _test\.go
      linters:
        - gomnd

  exclude-use-default: false
  exclude:
    # Exclude some common false positives
    - "G404" # Use of weak random number generator (not security critical)
    - "G501" # Import blacklist: crypto/md5 (needed for some LaTeX compatibility)