# PhD Dissertation Planner - Goreleaser Configuration
# https://goreleaser.com

version: 2

project_name: phd-dissertation-planner

# Build customization
builds:
  - main: ./cmd/planner
    binary: plannergen
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath

# Archive customization
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

# Checksum customization
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  extra_files:
    - glob: '*.tar.gz'
    - glob: '*.zip'

# Changelog customization
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - 'Merge pull request'
      - 'Merge branch'

# Release customization
release:
  name_template: "{{.Tag}}"
  github:
    owner: guitarbeat
    name: gantt
  prerelease: auto
  mode: append
  header: |
    ## 🚀 PhD Dissertation Planner {{.Tag}} - Release Notes

    Welcome to the latest release of PhD Dissertation Planner!

    ### 📋 What's New
  footer: |
    ---

    ## 🤝 Contributing

    We welcome contributions! Please see our [Contributing Guide](https://github.com/aaronang/phd-dissertation-planner/blob/main/CONTRIBUTING.md) for details.

    ## 📞 Support

    If you encounter any issues, please [open an issue](https://github.com/aaronang/phd-dissertation-planner/issues) on GitHub.

    ---

    **Full Changelog**: https://github.com/aaronang/phd-dissertation-planner/compare/{{.PreviousTag}}...{{.Tag}}

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/guitarbeat/gantt:{{ .Tag }}-amd64"
      - "ghcr.io/guitarbeat/gantt:v{{ .Major }}-amd64"
      - "ghcr.io/guitarbeat/gantt:latest-amd64"
    dockerfile: Dockerfile.dev
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=PhD Dissertation Planner"
      - "--label=org.opencontainers.image.description=Academic planning tool for PhD dissertations"
      - "--label=org.opencontainers.image.source=https://github.com/aaronang/phd-dissertation-planner"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "ghcr.io/guitarbeat/gantt:{{ .Tag }}-arm64"
      - "ghcr.io/guitarbeat/gantt:v{{ .Major }}-arm64"
      - "ghcr.io/guitarbeat/gantt:latest-arm64"
    dockerfile: Dockerfile.dev
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=PhD Dissertation Planner"
      - "--label=org.opencontainers.image.description=Academic planning tool for PhD dissertations"
      - "--label=org.opencontainers.image.source=https://github.com/aaronang/phd-dissertation-planner"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goarch: arm64

# Multi-arch Docker manifest
docker_manifests:
  - name_template: "ghcr.io/guitarbeat/gantt:{{ .Tag }}"
    image_templates:
      - "ghcr.io/guitarbeat/gantt:{{ .Tag }}-amd64"
      - "ghcr.io/guitarbeat/gantt:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/guitarbeat/gantt:v{{ .Major }}"
    image_templates:
      - "ghcr.io/guitarbeat/gantt:v{{ .Major }}-amd64"
      - "ghcr.io/guitarbeat/gantt:v{{ .Major }}-arm64"

  - name_template: "ghcr.io/guitarbeat/gantt:latest"
    image_templates:
      - "ghcr.io/guitarbeat/gantt:latest-amd64"
      - "ghcr.io/guitarbeat/gantt:latest-arm64"

# Snapshot customization
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# GitHub Actions integration
github:
  - name: release
    if: event.type == 'published' && event.action == 'released'
    uses: goreleaser/goreleaser-action@v5
    with:
      distribution: goreleaser
      version: latest
      args: release --clean
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

# Before hooks
before:
  hooks:
    - go mod tidy
    - go generate ./...

# After hooks
after:
  hooks:
    - echo "Release {{.Tag}} published successfully!"
