# Build customization
project_name: phd-dissertation-planner

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - main: ./cmd/planner
    binary: plannergen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aaron-schein
    name: phd-dissertation-planner
  name_template: "PhD Dissertation Planner v{{.Version}}"

brews:
  - name: phd-dissertation-planner
    repository:
      owner: aaron-schein
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://github.com/aaron-schein/phd-dissertation-planner"
    description: "A Go-based application that transforms CSV data into professional LaTeX-generated PDF planners and Gantt charts for academic project management"
    license: "MIT"
    test: |
      system "#{bin}/plannergen --version"

scoop:
  bucket:
    owner: aaron-schein
    name: scoop-bucket
  homepage: "https://github.com/aaron-schein/phd-dissertation-planner"
  description: "A Go-based application that transforms CSV data into professional LaTeX-generated PDF planners and Gantt charts for academic project management"
  license: "MIT"

dockers:
  - image_templates:
      - "ghcr.io/aaron-schein/phd-dissertation-planner:{{ .Tag }}"
      - "ghcr.io/aaron-schein/phd-dissertation-planner:v{{ .Major }}"
      - "ghcr.io/aaron-schein/phd-dissertation-planner:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/aaron-schein/phd-dissertation-planner:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - input_data/
      - configs/
