weekstart: 1
ampmtime: false
dotted: true
calafterschedule: false
addlasthalfhour: true

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 0.2cm
      bottom: 0.5cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.1

  lengths:
    tabcolsep: 3.5pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 70pt
    headerresizebox: 6mm
    headersidemonthswidth: 14.5cm

  colors:
    gray: gray
    lightgray: gray!50
