layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    margin:
      top: 1.2cm
      bottom: 0.7cm
      left: 0.5cm
      right: 0.5cm

    reversemargins: true
    marginparwidth: .8cm
    marginparsep: 3mm

  lengths:
    quarterlyspring: \textcolor{white}{.}
