weekstart: 1
ampmtime: false
dotted: true
calafterschedule: false
addlasthalfhour: true
cleartoprightcorner: false

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 0.2cm
      bottom: 0.5cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.1

  lengths:
    tabcolsep: 3pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 78pt
    headerresizebox: 6mm
    headersidemonthswidth: 14.5cm

  colors:
    gray: gray
    lightgray: gray!50

  # LaTeX visual constants
  latex:
    tabcolsep: 3.5pt
    headersidemonthswidth: 14.5cm
    taskborderwidth: 0.6pt
    taskpaddingh: 1.5mm
    taskpaddingv: 0.5mm
    taskverticaloffset: 0.7mm
    arraystretch: 1.2

  # Layout constraints for task positioning
  constraints:
    maxstackheight: 100.0
    mintaskheight: 20.0
    maxtaskheight: 40.0
    mintaskwidth: 50.0
    maxtaskwidth: 200.0
    verticalspacing: 2.0
    horizontalspacing: 5.0
    collisionthreshold: 0.1
    overflowthreshold: 0.8
    expansionthreshold: 0.6
