pages:
  - name: phases
    renderblocks:
      - funcname: phases
        tpls:
          - phases_page.tpl
  - name: monthly
    renderblocks:
      - funcname: monthly
        tpls:
          - page.tpl
