# Device-specific configuration profiles
# Inspired by latex-yearly-planner device optimizations

profiles:
  # E-ink device profiles
  supernote_a5x:
    name: "Supernote A5X"
    description: "Optimized for Supernote A5X e-ink tablet"
    device_type: "eink"
    screen_size: "a5"
    resolution: "1404x1872"
    optimizations:
      - "high_contrast_colors"
      - "thick_lines"
      - "large_fonts"
      - "minimal_graphics"
      - "touch_friendly_spacing"
    layout:
      page_size: "a5paper"
      orientation: "portrait"
      margin: "0.3in"
      font_size: "12pt"
      line_thickness: "1.5pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [0, 0, 0]
      grid: [200, 200, 200]
    
  remarkable_2:
    name: "ReMarkable 2"
    description: "Optimized for ReMarkable 2 e-ink tablet"
    device_type: "eink"
    screen_size: "a4"
    resolution: "1404x1872"
    optimizations:
      - "high_contrast_colors"
      - "thick_lines"
      - "large_fonts"
      - "minimal_graphics"
      - "touch_friendly_spacing"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.4in"
      font_size: "11pt"
      line_thickness: "1.2pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [0, 0, 0]
      grid: [180, 180, 180]
    
  boox_max_lumi:
    name: "Boox Max Lumi"
    description: "Optimized for Boox Max Lumi large e-ink tablet"
    device_type: "eink"
    screen_size: "a4"
    resolution: "1650x2200"
    optimizations:
      - "high_contrast_colors"
      - "thick_lines"
      - "large_fonts"
      - "minimal_graphics"
      - "touch_friendly_spacing"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.5in"
      font_size: "12pt"
      line_thickness: "1.0pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [0, 0, 0]
      grid: [160, 160, 160]

  # Print device profiles
  standard_print:
    name: "Standard Print"
    description: "Optimized for standard office/home printing"
    device_type: "print"
    media: "paper"
    size: "a4"
    optimizations:
      - "print_safe_colors"
      - "standard_margins"
      - "bleed_areas"
      - "binding_margins"
      - "high_resolution_graphics"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.5in"
      font_size: "10pt"
      line_thickness: "0.8pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [59, 130, 246]
      grid: [200, 200, 200]
    
  professional_print:
    name: "Professional Print"
    description: "Optimized for professional printing and binding"
    device_type: "print"
    media: "paper"
    size: "a4"
    optimizations:
      - "print_safe_colors"
      - "binding_margins"
      - "bleed_areas"
      - "high_resolution_graphics"
      - "professional_typography"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.75in"
      font_size: "11pt"
      line_thickness: "0.6pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [31, 41, 55]
      grid: [180, 180, 180]
    
  large_format_print:
    name: "Large Format Print"
    description: "Optimized for large format printing (A3, A2)"
    device_type: "print"
    media: "paper"
    size: "a3"
    optimizations:
      - "print_safe_colors"
      - "large_format_margins"
      - "bleed_areas"
      - "high_resolution_graphics"
      - "scalable_elements"
    layout:
      page_size: "a3paper"
      orientation: "landscape"
      margin: "0.5in"
      font_size: "12pt"
      line_thickness: "1.0pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [59, 130, 246]
      grid: [200, 200, 200]

  # Digital device profiles
  desktop_pdf:
    name: "Desktop PDF"
    description: "Optimized for desktop PDF viewing and annotation"
    device_type: "digital"
    platform: "desktop"
    screen_type: "lcd"
    optimizations:
      - "screen_friendly_colors"
      - "interactive_elements"
      - "zoom_friendly_layout"
      - "annotation_spaces"
      - "hyperlinks"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.5in"
      font_size: "10pt"
      line_thickness: "0.8pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [59, 130, 246]
      grid: [220, 220, 220]
    
  tablet_pdf:
    name: "Tablet PDF"
    description: "Optimized for tablet PDF viewing and annotation"
    device_type: "digital"
    platform: "tablet"
    screen_type: "lcd"
    optimizations:
      - "touch_friendly_spacing"
      - "screen_friendly_colors"
      - "interactive_elements"
      - "zoom_friendly_layout"
      - "annotation_spaces"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.4in"
      font_size: "11pt"
      line_thickness: "1.0pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [59, 130, 246]
      grid: [200, 200, 200]
    
  mobile_pdf:
    name: "Mobile PDF"
    description: "Optimized for mobile PDF viewing"
    device_type: "digital"
    platform: "mobile"
    screen_type: "lcd"
    optimizations:
      - "mobile_friendly_layout"
      - "large_touch_targets"
      - "screen_friendly_colors"
      - "simplified_graphics"
      - "readable_fonts"
    layout:
      page_size: "a4paper"
      orientation: "portrait"
      margin: "0.3in"
      font_size: "12pt"
      line_thickness: "1.2pt"
    colors:
      background: [255, 255, 255]
      text: [0, 0, 0]
      accent: [59, 130, 246]
      grid: [180, 180, 180]

# Default device profile
default_profile: "standard_print"

# Device detection and auto-selection
auto_detect:
  enabled: true
  fallback: "standard_print"
  detection_rules:
    - condition: "output_format == 'pdf' and device_type == 'eink'"
      profile: "supernote_a5x"
    - condition: "output_format == 'pdf' and device_type == 'print'"
      profile: "standard_print"
    - condition: "output_format == 'pdf' and device_type == 'digital'"
      profile: "desktop_pdf"
