# LaTeX Gantt Chart Generator - Template Configuration
# Inspired by latex-yearly-planner template system

templates:
  # Main template types
  gantt_timeline:
    name: "Gantt Timeline"
    description: "Vertical timeline with task bars and dependencies"
    layout: "vertical"
    orientation: "portrait"
    page_size: "a4paper"
    margin: "0.5in"
    features:
      - "task_bars"
      - "dependencies"
      - "milestones"
      - "status_indicators"
      - "priority_markers"
    
  monthly_calendar:
    name: "Monthly Calendar"
    description: "Monthly grid view with task overlays"
    layout: "grid"
    orientation: "landscape"
    page_size: "a4paper"
    margin: "0.3in"
    features:
      - "monthly_grid"
      - "task_overlays"
      - "milestone_markers"
      - "week_numbers"
      - "holiday_indicators"
    
  weekly_planner:
    name: "Weekly Planner"
    description: "Weekly view with detailed task scheduling"
    layout: "weekly"
    orientation: "landscape"
    page_size: "a4paper"
    margin: "0.4in"
    features:
      - "weekly_grid"
      - "time_slots"
      - "task_scheduling"
      - "notes_sections"
      - "priority_areas"
    
  daily_agenda:
    name: "Daily Agenda"
    description: "Daily detailed view with hourly breakdown"
    layout: "daily"
    orientation: "portrait"
    page_size: "a4paper"
    margin: "0.5in"
    features:
      - "hourly_grid"
      - "task_details"
      - "notes_space"
      - "progress_tracking"
      - "reflection_sections"

# Device-specific optimizations
devices:
  eink:
    name: "E-ink Devices"
    description: "Optimized for Supernote, ReMarkable, and other e-ink devices"
    optimizations:
      - "high_contrast_colors"
      - "thick_lines"
      - "large_fonts"
      - "minimal_graphics"
      - "touch_friendly_spacing"
    
  print:
    name: "Print Optimization"
    description: "Optimized for standard printing"
    optimizations:
      - "print_safe_colors"
      - "standard_margins"
      - "bleed_areas"
      - "binding_margins"
      - "high_resolution_graphics"
    
  digital:
    name: "Digital Viewing"
    description: "Optimized for screen viewing and PDF annotation"
    optimizations:
      - "screen_friendly_colors"
      - "interactive_elements"
      - "zoom_friendly_layout"
      - "annotation_spaces"
      - "hyperlinks"

# Layout configurations
layouts:
  vertical_timeline:
    name: "Vertical Timeline"
    description: "Tasks arranged vertically with time axis on left"
    axis_orientation: "vertical"
    task_placement: "horizontal_bars"
    time_scale: "months"
    grid_lines: "weekly"
    
  horizontal_timeline:
    name: "Horizontal Timeline"
    description: "Tasks arranged horizontally with time axis on top"
    axis_orientation: "horizontal"
    task_placement: "vertical_bars"
    time_scale: "months"
    grid_lines: "weekly"
    
  calendar_grid:
    name: "Calendar Grid"
    description: "Traditional calendar layout with task overlays"
    axis_orientation: "grid"
    task_placement: "overlay"
    time_scale: "days"
    grid_lines: "daily"
    
  kanban_board:
    name: "Kanban Board"
    description: "Task columns organized by status or category"
    axis_orientation: "columns"
    task_placement: "cards"
    time_scale: "none"
    grid_lines: "none"

# Color schemes
color_schemes:
  academic:
    name: "Academic"
    description: "Professional colors for academic and research use"
    colors:
      primary: [59, 130, 246]      # Blue
      secondary: [16, 185, 129]    # Green
      accent: [245, 158, 11]       # Orange
      neutral: [107, 114, 128]     # Gray
      success: [34, 197, 94]       # Green
      warning: [251, 146, 60]      # Orange
      error: [239, 68, 68]         # Red
      info: [59, 130, 246]         # Blue
    
  corporate:
    name: "Corporate"
    description: "Professional colors for business and corporate use"
    colors:
      primary: [31, 41, 55]        # Dark gray
      secondary: [75, 85, 99]      # Medium gray
      accent: [59, 130, 246]       # Blue
      neutral: [156, 163, 175]     # Light gray
      success: [34, 197, 94]       # Green
      warning: [251, 146, 60]      # Orange
      error: [239, 68, 68]         # Red
      info: [59, 130, 246]         # Blue
    
  vibrant:
    name: "Vibrant"
    description: "Bright, colorful scheme for creative projects"
    colors:
      primary: [147, 51, 234]      # Purple
      secondary: [236, 72, 153]    # Pink
      accent: [16, 185, 129]       # Green
      neutral: [156, 163, 175]     # Gray
      success: [34, 197, 94]       # Green
      warning: [251, 146, 60]      # Orange
      error: [239, 68, 68]         # Red
      info: [59, 130, 246]         # Blue

# Font configurations
fonts:
  serif:
    name: "Serif"
    description: "Traditional serif fonts for formal documents"
    main_font: "lmodern"
    sans_font: "helvet"
    mono_font: "courier"
    
  sans_serif:
    name: "Sans Serif"
    description: "Modern sans-serif fonts for clean, readable documents"
    main_font: "helvet"
    sans_font: "helvet"
    mono_font: "courier"
    
  modern:
    name: "Modern"
    description: "Contemporary fonts for modern documents"
    main_font: "lmodern"
    sans_font: "helvet"
    mono_font: "courier"

# Default configuration
defaults:
  template: "gantt_timeline"
  device: "print"
  layout: "vertical_timeline"
  color_scheme: "academic"
  font: "sans_serif"
  language: "en"
  timezone: "UTC"
