weekstart: 1
ampmtime: false
dotted: true
calafterschedule: false
addlasthalfhour: true
cleartoprightcorner: false

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 0.2cm
      bottom: 0.5cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.1

  lengths:
    tabcolsep: 3pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 78pt
    headerresizebox: 6mm
    headersidemonthswidth: 14.5cm

  colors:
    gray: gray
    lightgray: gray!50

  # Task category colors (RGB components)
  task_colors:
    proposal:
      r: 74
      g: 144
      b: 226
    laser:
      r: 245
      g: 166
      b: 35
    imaging:
      r: 126
      g: 211
      b: 33
    admin:
      r: 189
      g: 16
      b: 224
    dissertation:
      r: 208
      g: 2
      b: 27
    research:
      r: 80
      g: 227
      b: 194
    publication:
      r: 184
      g: 233
      b: 134

  # LaTeX visual constants
  latex:
    tabcolsep: 3.5pt
    headersidemonthswidth: 14.5cm
    taskborderwidth: 0.6pt
    taskpaddingh: 1.5mm
    taskpaddingv: 0.5mm
    taskverticaloffset: 0.7mm
    arraystretch: 1.2
    taskfontsize: \small
    taskbarheight: 4mm
    monthlycellheight: 78pt
    headerresizebox: 6mm
    linethicknessdefault: .4pt
    linethicknessthick: .8pt

    # Task styling parameters
    task_background_opacity: 20
    task_border_opacity: 80
    task_content_spacing: "0.2ex"

    # TColorBox styling parameters
    tcolorbox:
      arc: 9pt
      left: 1.5mm
      right: 1.5mm
      top: 1.0mm
      bottom: 1.0mm
      boxrule: 0.9pt
      taskboxrule: 0.7pt
      taskarc: 8pt
      taskleft: 1.2mm
      taskright: 1.2mm
      tasktop: 0.8mm
      taskbottom: 0.8mm

    # Typography settings
    typography:
      hyphenpenalty: 50
      tolerance: 1000
      emergencystretch: 2em
      sloppyemergencystretch: 3em

    # Spacing and layout
    spacing:
      twocolsep: 5pt
      tricolsep: 5pt
      fivecolsep: 5pt
      tablecolsep: 0.5em
      colorlegendsep: 1.5em
      pagebreak: \pagebreak

    # Document settings
    document:
      fontsize: 9pt
      parindent: 0pt
      fboxsep: 0pt

  # Layout constraints for task positioning
  constraints:
    maxstackheight: 100.0
    mintaskheight: 20.0
    maxtaskheight: 40.0
    mintaskwidth: 50.0
    maxtaskwidth: 200.0
    verticalspacing: 2.0
    horizontalspacing: 5.0
    collisionthreshold: 0.1
    overflowthreshold: 0.8
    expansionthreshold: 0.6

    # Task sizing multipliers (relative to day dimensions)
    min_task_height_multiplier: 0.5
    max_task_height_multiplier: 2.0
    min_task_width_multiplier: 0.1
    max_task_width_days: 7.0  # Maximum task width in days

    # Visual styling
    task_bar_opacity: 1.0
    border_width: 0.5
    opacity_threshold: 0.999

    # Algorithm thresholds
    compression_threshold: 0.8
    quality_threshold: 0.8
    balance_threshold: 0.7
    efficiency_threshold: 0.5
    efficiency_good_threshold: 0.9

    # Task positioning
    task_vertical_offset: 0.0
    task_horizontal_offset: 0.0
    expanded_task_vertical_offset: 5.0
    expanded_task_horizontal_offset: 5.0
    expanded_task_height_multiplier: 0.8
    expanded_task_width_multiplier: 0.8
    collapsed_task_height_multiplier: 0.5
    collapsed_task_width_multiplier: 0.5

  # Calendar rendering parameters
  calendar:
    daynumberwidth: 6mm
    daycontentmargin: 8mm
    taskkernspacing: 5mm
    collapse_threshold: 5
    taskbar_opacity: 1.0
    border_width: 0.5

    # Typography settings for calendar content
    emergencystretch: 3em
    inner_sep: 2pt

    # Cell rendering parameters
    day_cell_minipage_width: 6mm
    task_cell_margin: 8mm
    task_cell_spacing: 6mm

    # Task rendering parameters
    max_task_chars: 16
    max_task_chars_compact: 13
    max_task_chars_very_compact: 10
    default_task_spacing: "0.8ex"
    first_task_spacing: "0.5ex"
    default_task_height: "3.0ex"
    first_task_height: "3.5ex"

  # Stacking algorithm parameters
  stacking:
    base_height: 20.0
    min_height: 15.0
    max_height: 60.0

    # Prominence multipliers
    prominence_critical: 1.5
    prominence_high: 1.3
    prominence_medium: 1.0
    prominence_low: 1.0
    prominence_minimal: 1.0

    # Duration-based weighting
    duration_short_weight: 1.0   # < 1 day
    duration_medium_weight: 1.0  # 1-7 days
    duration_long_weight: 1.2    # > 7 days

    # Complexity-based weighting
    complexity_minimal_weight: 1.0
    complexity_normal_weight: 1.0
    complexity_complex_weight: 1.3

    # Task positioning parameters
    vertical_spacing: 2.0
    horizontal_spacing: 5.0

    # Visual quality thresholds
    visibility_threshold: 0.5
    overflow_vertical: 0.8
    collision_threshold: 0.1
    bounding_box_buffer: 2.0

    # Quality assessment thresholds
    quality_high_threshold: 0.8
    balance_high_threshold: 0.7
    compression_high_threshold: 0.5

    # Weight calculation parameters
    duration_weight_factor: 0.01
    category_high_weight: 2.0
    category_medium_weight: 1.5
    category_normal_weight: 1.0
    category_high_bonus: 3.0

