weekstart: 1
ampmtime: false
dotted: true
calafterschedule: false
addlasthalfhour: true
cleartoprightcorner: false

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 0.2cm
      bottom: 0.5cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.1

  lengths:
    lineheightbutline: \dimexpr5mm-.4pt

  colors:
    gray: gray
    lightgray: gray!50

  # Task category colors are now generated algorithmically
  # Colors are consistent and visually distinct based on category name hash

  # LaTeX visual constants
  latex:
    tabcolsep: 3.5pt
    headersidemonthswidth: 14.5cm
    taskborderwidth: 0.6pt
    taskpaddingh: 1.5mm
    taskpaddingv: 0.5mm
    taskverticaloffset: 0.7mm
    arraystretch: 1.2
    taskfontsize: \small
    taskbarheight: 4mm
    monthlycellheight: 78pt
    headerresizebox: 6mm
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    colsep: 5pt

    # Task styling parameters
    task_background_opacity: 20
    task_border_opacity: 80
    task_content_spacing: "0.2ex"

    # TColorBox styling parameters
    tcolorbox:
      arc: 9pt
      left: 1.5mm
      right: 1.5mm
      top: 1.0mm
      bottom: 1.0mm
      boxrule: 0.9pt
      taskboxrule: 0.7pt
      taskarc: 8pt
      taskleft: 1.2mm
      taskright: 1.2mm
      tasktop: 0.8mm
      taskbottom: 0.8mm

    # Typography settings
    typography:
      hyphenpenalty: 50
      tolerance: 1000
      emergencystretch: 2em
      sloppyemergencystretch: 3em

    # Spacing and layout
    spacing:
      tablecolsep: 0.5em
      colorlegendsep: 1.5em
      pagebreak: \pagebreak
      verticalspacing: 2.0
      horizontalspacing: 5.0
      # Template-specific spacing values
      col: "5pt"
      task_content_vspace: "0.2ex"
      task_overlay_arc: "2pt"

    # Document settings
    document:
      fontsize: 9pt
      parindent: 0pt
      fboxsep: 0pt

  # Layout constraints for task positioning
  constraints:
    maxstackheight: 100.0
    mintaskheight: 20.0
    maxtaskheight: 40.0
    mintaskwidth: 50.0
    maxtaskwidth: 200.0
    collisionthreshold: 0.1
    overflowthreshold: 0.8
    expansionthreshold: 0.6

    # Task sizing multipliers (relative to day dimensions)
    min_task_height_multiplier: 0.5
    max_task_height_multiplier: 2.0
    min_task_width_multiplier: 0.1
    max_task_width_days: 7.0  # Maximum task width in days

    # Visual styling (inherited from layout_engine)

    # Algorithm thresholds (inherited from layout_engine)

    # Task positioning
    task_vertical_offset: 0.0
    task_horizontal_offset: 0.0
    expanded_task_vertical_offset: 5.0
    expanded_task_horizontal_offset: 5.0
    expanded_task_height_multiplier: 0.8
    expanded_task_width_multiplier: 0.8
    collapsed_task_height_multiplier: 0.5
    collapsed_task_width_multiplier: 0.5

  # Calendar rendering parameters
  calendar:
    daynumberwidth: 6mm
    daycontentmargin: 8mm
    taskkernspacing: 5mm
    collapse_threshold: 5
    # Visual styling (inherited from layout_engine)

    # Typography settings for calendar content
    emergencystretch: 3em
    inner_sep: 2pt

    # Cell rendering parameters
    day_cell_minipage_width: 6mm
    task_cell_margin: 8mm
    task_cell_spacing: 6mm

    # Task rendering parameters (inherited from layout_engine)

  # Stacking algorithm parameters
  stacking:
    base_height: 20.0
    min_height: 15.0
    max_height: 60.0

    # Visual quality thresholds
    visibility_threshold: 0.5
    overflow_vertical: 0.8
    collision_threshold: 0.1
    bounding_box_buffer: 2.0

    # Visual weight defaults
    default_visual_weight: 0.5
    default_prominence_score: 0.5

  # Layout engine specific parameters
  layout_engine:
    # Task positioning multipliers (relative to day dimensions)
    initial_y_position_multiplier: 0.1  # 10% from top of day
    task_height_multiplier: 0.6         # 60% of day height
    max_task_width_days: 7.0            # Maximum task width in days
    
    # Visual weight calculation multipliers
    duration_long_multiplier: 1.2       # For tasks > 7 days
    duration_short_multiplier: 0.8      # For tasks < 1 day
    milestone_weight_multiplier: 1.5    # For milestone tasks
    category_weight_multiplier: 1.0     # Base category weight
    
    
    # Task rendering configuration
    task_rendering:
      default_spacing: "0.8ex"
      first_task_spacing: "0.5ex"
      default_height: "3.0ex"
      first_task_height: "3.5ex"
      vertical_spacing: "0.1ex"
    
    # Typography settings for task text (inherited from main typography)
    
    # Grid constraints
    grid_constraints:
      min_task_spacing: 1.0
      max_task_spacing: 10.0
      min_row_height: 8.0
      max_row_height: 20.0
      min_column_width: 5.0
      max_column_width: 50.0
      grid_resolution: 1.0
      alignment_tolerance: 0.5
      collision_buffer: 2.0
      transition_buffer: 2.0
    
    # Visual styling
    visual_styling:
      task_bar_opacity: 1.0
      task_bar_opacity_fallback: 0.9
      border_width: 0.5
      opacity_threshold: 0.999
      inner_sep: "2pt"
    
    # Calendar layout constants
    calendar_layout:
      day_number_width: "6mm"
      day_content_margin: "8mm"
      task_cell_margin: "8mm"
      task_cell_spacing: "6mm"
      day_cell_minipage_width: "6mm"
      header_angle_size_offset: "0.86pt"
    
    # Task density calculation removed - not used in code

pages:
  - name: monthly
    renderblocks:
      - funcname: monthly
        tpls:
          - page.tpl

