name: Build Planner PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install XeLaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xz-utils \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-plain-generic \
            lmodern

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: planner-outputs
          path: |
            output/*.pdf
            output/*.tex
            output/*.log
          if-no-files-found: warn


